### PR TITLE
Clear the sidebar UI

### LINKED ISSUE #168: Breakpoints not removed from the sidebar on notebook closed
When a notebook is closed, the breakpoints stay in the sidebar and are not removed.

Clicking on "Remove All Breakpoints" throws the following error:

```
Uncaught (in promise) Error: A kernel is required to send debug messages.
```

breakpoints-notebook-closed

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #168.

Alternative to #291. 

This introduces a new `clear()` method on the model to clear everything, and restore the breakpoints to an empty map.

This should also still support keeping the last debug session alive when switching between notebooks and widgets.

clear-sidebar-ui

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -194,6 +194,14 @@ class DebuggerHandler<
       }
       handler.dispose();
       delete this._handlers[widget.id];
+
+      // clear the model if the handler being removed corresponds
+      // to the current active debug session
+      if (debug.session?.client?.path === client.path) {
+        const model = debug.model as Debugger.Model;
+        model.clear();
```
Comment (jtpio) [inline src/index.ts]: There could be a call to `debug.stop()` instead, so this would also handle the case when the execution has stopped.

But when the notebook is disposed, its kernel (via `client.kernel`) is already set to `null`, which prevents sending the `disconnect` message.

Also, stopping the debugger wouldn't play nice when two notebooks are using the same kernel.

**Comment by jtpio** [comment]
cc @KsavinN let me know what you think.

This takes a slightly different approach than #291 and tries to not be too specific to breakpoints.

**Comment by KsavinN** [comment]
It looks definitely better. I will test that locally :)

**Comment by jtpio** [comment]
Cool :)

The tricky part about clearing the model is that we still want to keep track of the previous active debug session (to enable debugging a notebook while looking at another one), if available.

**Comment by KsavinN** [comment]
Tested Locally, we can merge it
